name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Building the Docker image
        run: docker build . --file Dockerfile --tag opticsquid/hangout-web-new:$(date +%s)
